---
title: "Untitled"
author: "Keliang Xu"
date: "2/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(openxlsx)
library(reshape2)
library(dplyr)
```


```{r}
#read data
data<-read.xlsx("for_stats_peeps.xlsx")
data<-data[,-2:-6]
data<-data[,-4]
data <- na.omit(data)
```

```{r}
#tidy data
data2<-data[,2:8]
data2<-data2[,-3]
data2<-data2[,-5]
aggdata<-melt(data2,id=(c("Taxa","Site")))

```


```{r}
#EDA



ggplot(data = aggdata, aes(x=variable,y=value, fill=variable)) + 
  geom_boxplot()+
  geom_jitter(shape=16, position=position_jitter(0.2))+
  facet_wrap(~Taxa,nrow = 1)


```


```{r}


ggplot(data = aggdata, aes(x=Taxa,y=value, fill=Taxa)) + 
  geom_boxplot()+
  geom_jitter(shape=16, position=position_jitter(0.2))+
  facet_wrap(~variable,nrow = 1)

```


```{r}
data_deer<-aggdata[which(aggdata$Taxa=="Deer"),]
data_Cottontail<-aggdata[which(aggdata$Taxa=="Cottontail"),]
data_Hare<-aggdata[which(aggdata$Taxa=="Hare"),]
data_Turkey<-aggdata[which(aggdata$Taxa=="Turkey"),]

deer1<-ggplot(data = data_deer, aes(x=variable,y=value, fill=variable)) + 
  geom_boxplot()+
  #geom_jitter(shape=16, position=position_jitter(0.2))+
  labs(title = 'Deer')+
  facet_wrap(~Site,nrow = 1)

deer2<-ggplot(data = data_deer, aes(x=Site,y=value, fill=Site)) + 
  geom_boxplot()+
  #geom_jitter(shape=16, position=position_jitter(0.2))+
  labs(title = 'Deer')+
  facet_wrap(~variable,nrow = 1)



cot1<-ggplot(data = data_Cottontail, aes(x=variable,y=value, fill=variable)) + 
  geom_boxplot()+
  #geom_jitter(shape=16, position=position_jitter(0.2))+
  labs(title = 'Cottontail')+
  facet_wrap(~Site,nrow = 1)

cot2<-ggplot(data = data_Cottontail, aes(x=Site,y=value, fill=Site)) + 
  geom_boxplot()+
  #geom_jitter(shape=16, position=position_jitter(0.2))+
  labs(title = 'Cottontail')+
  facet_wrap(~variable,nrow = 1)


hare1<-ggplot(data = data_Hare, aes(x=variable,y=value, fill=variable)) + 
  geom_boxplot()+
  #geom_jitter(shape=16, position=position_jitter(0.2))+
  labs(title = 'Hare')+
  facet_wrap(~Site,nrow = 1)

hare2<-ggplot(data = data_Hare, aes(x=Site,y=value, fill=Site)) + 
  geom_boxplot()+
  #geom_jitter(shape=16, position=position_jitter(0.2))+
  labs(title = 'Hare')+
  facet_wrap(~variable,nrow = 1)

turkey1<-ggplot(data = data_Turkey, aes(x=variable,y=value, fill=variable)) + 
  geom_boxplot()+
  #geom_jitter(shape=16, position=position_jitter(0.2))+
  labs(title = 'Turkey')+
  facet_wrap(~Site,nrow = 1)

turkey2<-ggplot(data = data_Turkey, aes(x=Site,y=value, fill=Site)) + 
  geom_boxplot()+
  #geom_jitter(shape=16, position=position_jitter(0.2))+
  labs(title = 'Turkey')+
  facet_wrap(~variable,nrow = 1)

```

```{r}

gridExtra::grid.arrange(deer1,cot1,nrow=2,ncol=1)
gridExtra::grid.arrange(hare1,turkey1,nrow=2,ncol=1)

gridExtra::grid.arrange(deer2,cot2,nrow=2,ncol=1)
gridExtra::grid.arrange(hare2,turkey2,nrow=2,ncol=1)

```

